### ISSUE TITLE
Error on line 30:56: TypeError: undefined is not an object (evaluating 'data.data.bzclxx')

### ISSUE THREAD

**Issue by krsmzzz** [bihongfly/jinjingzheng#3]
请教下大佬scriplate配置完URL提示这个怎么解决，是还有什么东西没配吗![image](https://github.com/bihongfly/jinjingzheng/assets/26400951/e65a7b70-716d-47f7-8719-7ec9cee46529)

**Comment by bihongfly** [comment]
你配置token了吗？ 102行有个auth

**Comment by Lantern-ty** [comment]
我也是这个问题，怎么解决呢？
