### ISSUE TITLE
大佬，self.auth配置了内容，但是脚本一运行就会显示令牌为空

### ISSUE THREAD

**Issue by rebootbrs** [bihongfly/jinjingzheng#4]
![image](https://github.com/bihongfly/jinjingzheng/assets/105451437/82708e5e-1fbd-485f-b62d-0ec2413b9ff8)
是什么原因呢，感谢

**Comment by bihongfly** [comment]
你打开app重新抓包看一下Authorization  这个报错基本是Authorization错误

**Comment by rebootbrs** [comment]
我是用小黄鸟抓的，刷新取了四五次不同的Authorization值，都显示这个问题，这个有加密吗？还是这个软件抓的不严谨，我再试试别的软件

**Comment by rebootbrs** [comment]
我是用小黄鸟抓的，刷新取了四五次不同的Authorization值，都显示这个问题，这个有加密吗？还是这个软件抓的不严谨，我再试试别的软件

**Comment by bihongfly** [comment]
我复现了你的操作，不过需要一些时间去看一下新的auth的获取方式，有进度会尽快更新。目前测试之前的auth不受影响。

**Comment by rebootbrs** [comment]
感谢，我尝试下载了较老版本的APP，发现是可以使用的，虽然新老版本拿到的数据看起来很像

**Comment by bihongfly** [comment]
老版本的查询续签都不受影响，你可以用老版本抓到auth，然后再更新app后，你的自动化脚本也不会受影响

**Comment by forever1209** [comment]
之前的令牌莫名其妙掉了，刚抓了新的令牌显示可以用  不知道用多久会掉 新版进京证好像改规则了

**Comment by bihongfly** [comment]
是的 新增加了登录的接口 先手动申请吧 有空的时候看下怎么适配新版的

**Comment by forever1209** [comment]
到时候可以一起研究一下

**Comment by bihongfly** [comment]
可以再次尝试一下 登录之后抓取 目前看5天前抓取的还有效 打开app也会自动登录

**Comment by forever1209** [comment]
我也是前几天重新抓的目前没有掉线

**Comment by bihongfly** [comment]
应该是前几天跟京通统一账号管理 刚刚开始导致的  这几天打开app也不用重新登录了 可以先用着 有问题再讨论
