### ISSUE TITLE
stream抓包ios 拿不到auth

### ISSUE THREAD

**Issue by forever1209** [bihongfly/jinjingzheng#5]
大佬最近我用ios的抓包都是空数据，你那边还能抓到数据吗 还是得旧版的jjz的app才可以呀

**Comment by bihongfly** [comment]
1、打开进京证app 点一下申请进京证 下一步之类的 停止
2、再去看一下stream的抓包结果 注意要看pro开头的那些请求（不要看h5开头的）
3、抓包详情里有请求那一栏，然后看请求头部有Authorization

**Comment by forever1209** [comment]
它变了，和之前的不一样，我提供一下图片截图
![IMG_1094 PNG](https://github.com/user-attachments/assets/b945e14c-6d0b-4d18-a670-afdf0506a951)
